[package]
name = "tidk"
version = "0.1.2"
authors = ["Max Brown <mb39@sanger.ac.uk>"]
edition = "2018"

[dependencies]
bio = "*"
rust-htslib = { version = "*", default-features = false }
clap = "~2.33.0"
